### ISSUE TITLE
accessing undefined field unpack of global table

### ISSUE THREAD

**Issue by Artem3213212** [tarantool/luacheck#16] opened 2022-11-13 16:21 UTC
## test:
```lua
local a, b = table.unpack({1,2})
print(a, b)
```

## result:
```
lint_test.lua:1:14: accessing undefined field unpack of global table
```

**Comment by igormunkin** [comment] 2022-12-02 08:04
There is no function `table.unpack` in [`Lua 5.1`](https://www.lua.org/manual/5.1/index.html#index). This function was only introduced in [`Lua 5.2`](https://www.lua.org/manual/5.2/index.html#index). I believe you're either using invalid `std` value in your .luacheckrc or doing something wrong with Tarantool (that tries to comply Lua 5.1 reference manual as close as LuaJIT v2.1 does with `LUAJIT_ENABLE_LUA52COMPAT` flag disabled).

I can share a couple of wild guesses trying to fix your problem:
* You can replace all [`table.unpack`](https://www.lua.org/manual/5.2/manual.html#pdf-table.unpack) occurrences with [`unpack`](https://www.lua.org/manual/5.1/manual.html#pdf-unpack) function everywhere in your code
* You can try using `--std lua52` or `--std lua52c` while using `luacheck`

All in all closing this as not a bug.

**Closed as not planned by igormunkin** 2022-12-02 08:04 UTC
